import { Concert } from "../interfaces/concert";


export const CONCERTS: Concert[] = [
  {
    id: 1,
    title: 'Maldita Nerea',
    photo:  'https://www.cadenadial.com/wp-content/uploads/2022/09/maldita-nerea.jpg',
    day: 24,
    month: '-Mayo',
    city: 'Malaga',
    tickets: true,
  },
  {
    id: 2,
    title: 'Anastacia',
    photo:  'https://dynamicmedia.livenationinternational.com/Media/g/p/d/3aed0f6e-1d6c-4808-8fcb-7c7a29bc480e.jpg',
    day: 27,
    month: '-Mayo',
    city: 'Malaga',
    tickets: true,
  },
  {
    id: 3,
    title: 'Pablo López',
    photo:  'https://www.lecturas.com/medio/2020/09/30/pablo-lopez_4be7b047_800x800.jpg',
    day: 15,
    month: '-Abril',
    city: 'Sevilla',
    tickets: false,
  },
   {
    id: 4,
    title: 'Ara Malikian',
    photo:  'https://img2.rtve.es/i/?w=1600&i=1637081008817.jpg',
    day: 23,
    month: '-Septiembre',
    city: 'Castellon',
    tickets: true,
  }, {
    id: 5,
    title: 'Manuel Carrasco',
    photo:  'https://www.granadahoy.com/2021/04/28/ocio/Manuel-Carrasco-imagen-reciente_1569153418_137746236_667x375.jpg',
    day: 10,
    month: '-Octubre',
    city: 'Barcelona',
    tickets: true,
  },
  {
    id: 6,
    title: 'Pablo Alborán',
    photo:  'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/img-4695-preview-1655160553.jpg?crop=1.00xw:0.747xh;0,0.209xh&resize=980:*',
    day: 16,
    month: '-Junio',
    city: 'Bilbao',
    tickets: true,
  },
  {
    id: 7,
    title: 'Morat',
    photo:  'https://mmalaga.es/wp-content/uploads/2023/02/morat.jpg',
    day: 21,
    month: '-Julio',
    city: 'Málaga',
    tickets: false,
  },
  {
    id: 8,
    title: 'Bad Gyal',
    photo:  'https://images.sk-static.com/images/media/profile_images/artists/8901654/huge_avatar',
    day: 18,
    month: '-Octubre',
    city: 'Toledo',
    tickets: false,
  },
  {
    id: 9,
    title: 'Martirio y Chano',
    photo:  'https://d2cyzdatssrhg7.cloudfront.net/export/sites/default/ets/.content/products/img/00-00088pA.jpg?__locale=es',
    day: 29,
    month: '-Junio',
    city: 'Cordoba',
    tickets: true,
  },
]